version: '3.3'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    ports:
      - 9090:80
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /:/srv
      - /root/projects/filebrowser/database/filebrowser.db:/config/filebrowser.db
    restart: always

