version: "3.8"

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - "${PORT}:8080"
    volumes:
      - "${DOCKER_STATIC_HOSTING}:/data"
      - "./config:/config"
    environment:
      FB_BASEURL: "/filebrowser"
      FB_USERNAME: "${FB_USERNAME}"
      FB_PASSWORD: "${FB_PASSWORD}"
    restart: always
    networks:
      - https

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true

